@API_HostAddress = http://localhost:5197

POST {{API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "password123"
}
###
POST {{API_HostAddress}}/api/auth/signin
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "password123"
};
###